"""schema check

Revision ID: 5cc1141aa61b
Revises: ccfd0d3fb698
Create Date: 2025-12-22 10:08:54.466007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5cc1141aa61b'
down_revision: Union[str, Sequence[str], None] = 'ccfd0d3fb698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'transaction_ref',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index(op.f('ix_alerts_transaction_ref'), 'alerts', ['transaction_ref'], unique=False)
    op.alter_column('model_metrics', 'ml_precision',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('model_metrics', 'recall',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('model_metrics', 'f1_score',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('model_metrics', 'false_positive_rate',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('model_metrics', 'data_drift_percent',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('transactions', 'oldbalanceOrg',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transactions', 'newbalanceOrig',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transactions', 'oldbalanceDest',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transactions', 'newbalanceDest',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transactions', 'fraud_score',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'fraud_score',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('transactions', 'newbalanceDest',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('transactions', 'oldbalanceDest',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('transactions', 'newbalanceOrig',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('transactions', 'oldbalanceOrg',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=False)
    op.alter_column('model_metrics', 'data_drift_percent',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('model_metrics', 'false_positive_rate',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('model_metrics', 'f1_score',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('model_metrics', 'recall',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.alter_column('model_metrics', 'ml_precision',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_alerts_transaction_ref'), table_name='alerts')
    op.alter_column('alerts', 'transaction_ref',
               existing_type=sa.String(length=50),
               type_=mysql.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
